name: lite_storage
description: "A super-duper-mega-ultra-extra fast, light and synchronous key-value storage written."
version: 3.3.7
homepage: ''

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0